jobs:
  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
      - run: npm run lint
      # - run: npm run test
orbs:
  heroku: circleci/heroku@1.2.3
  node: circleci/node@4.1.0
version: 2.1
workflows:
  test-and-deploy:
    jobs:
      - lint
      - heroku/deploy-via-git:
          filters:
            branches:
              only:
                - master
          requires:
            - lint
